"""Tiny hand-labeled set for the lexicon engine. Not a public benchmark.

Labels are the intended polarity of clear sentences, including negation.
Accuracy is computed by tests/test_sentiment.py; do not hard-code a score.
"""

LABELED_SAMPLES: list[tuple[str, str]] = [
    ("这个视频太好看了，剪辑很棒", "positive"),
    ("支持up主，内容很有用", "positive"),
    ("讲得清楚，学到了很多", "positive"),
    ("画质音质都很好，三连了", "positive"),
    ("节奏舒服，期待下一期", "positive"),
    ("干货满满，必须安利给朋友", "positive"),
    ("笑死我了，太有才了", "positive"),
    ("字幕做得很用心，感谢分享", "positive"),
    ("这个选题真的绝了", "positive"),
    ("声音好听，解说专业", "positive"),
    ("终于更新了，爱了爱了", "positive"),
    ("很实用，值得推荐", "positive"),
    ("不是很难，讲得很清楚", "positive"),
    ("哈哈哈太搞笑了，有趣", "positive"),
    ("太拖沓了，看到一半就退出了", "negative"),
    ("标题党，内容和标题完全不符", "negative"),
    ("画质模糊，音质也差", "negative"),
    ("广告太多，恰饭恰得没边", "negative"),
    ("这价格也太贵了吧", "negative"),
    ("更新太慢了，又鸽了", "negative"),
    ("剪辑乱七八糟，根本看不下去", "negative"),
    ("无语，全是水文", "negative"),
    ("骗人的吧，数据明显夸张", "negative"),
    ("节奏太快，根本听不清", "negative"),
    ("互动太差，评论从来不回", "negative"),
    ("无聊透顶，浪费时间", "negative"),
    ("这个一点都不好看", "negative"),
    ("我不太喜欢这个节奏", "negative"),
    ("垃圾内容，恶心到想取关", "negative"),
    ("今天的视频讲了三个部分", "neutral"),
    ("这个分区我第一次看", "neutral"),
    ("视频时长大概十五分钟", "neutral"),
    ("背景音乐是哪一首", "neutral"),
    ("他用的软件是什么", "neutral"),
    ("评论区有人在讨论设定", "neutral"),
    ("这一期换了封面", "neutral"),
    ("发布时间是晚上", "neutral"),
    ("弹幕里提到了上一期", "neutral"),
    ("我是从首页点进来的", "neutral"),
    ("字幕在画面右下角", "neutral"),
    ("视频里出现了三个人", "neutral"),
]
